# Generated by Django 3.1.7 on 2021-04-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customusermodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='user_permissions',
        ),
    ]
