version: '3.7'
services:
  service:
    network_mode: host
    build:
      context: ./backend/service
      dockerfile: Dockerfile
    command: flask run
    ports:
      - 5000:5000
    volumes:
      - ./backend/service:/app_code
    env_file:
      - ./.env.dev
  django:
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    command: >
      sh -c "python backend/manage.py runserver 0.0.0.0:8080"
    volumes:
    - ./backend:/app
    environment:
      - DEBUG=1
    env_file:
      - ./.env.dev