version: '3.7'
services:
  service:
    network_mode: host
    build:
      context: ./backend
      dockerfile: service/Dockerfile
    command: python app.py
    volumes:
      - ./backend :/usr/src/backend
    ports:
      - 8000:5000
    env_file:
      - ./.env.dev