"""empty message

Revision ID: e20e23790ece
Revises: 
Create Date: 2021-02-17 17:48:19.345110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20e23790ece'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_descriptor'), 'user', ['descriptor'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_descriptor'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
